version: '3.8'

services:
  simpleapps-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"  # Exponer puerto HTTPS
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html/assets
      - ./ssl:/etc/nginx/ssl  # Montar certificados SSL
    networks:
      - simpleapps-network

networks:
  simpleapps-network:
    driver: bridge